export default {
    apartments: [ {
        _id: "111111111111111111111111",
        name: "Оренда двохкімнатної квартири",
        category: "Квартири",
        countRooms: "2 кімнати",
        TotalArea: "30м2",
        city: "Житомир",
        street: "Героїв Небесної сотні",
        totalAction: "Довгострокова",
        numberApartmentOrHouse: 33,
        furnitureAvailability: "З меблями",
        floor: 3,
        multimedia: "Wi-Fi, телевізор і т.д",
        householdAppliances: "Пральна машина",
        timeCreated: "12-05-2022",
        image: "/files/apartments/images/appartment_1.jpg",
        price: 300,
        Characteristics: "Text",
        rating: 4.5,
        numReviews: 10,
        StockIn: false,
    }, {
        _id: "222222222222222222222222",
        name: "Атмосферная квартира Винниченко 12",
        category: "Квартири",
        countRooms: "3 кімнати",
        TotalArea: "30м2",
        city: "Житомир",
        street: "Героїв Небесної сотні",
        totalAction: "Довгострокова",
        numberApartmentOrHouse: "22",
        furnitureAvailability: "З меблями",
        floor: 3,
        multimedia: "Wi-Fi, Телевізор, Швидкісний інтернет",
        householdAppliances: "Плита, Пральна машина",
        timeCreated: "12-05-2022",
        image: "/files/apartments/images/apartment_2.jpg",
        price: 3000,
        Characteristics: "Сдается в аренду 3к квартира, Шевченковский район, ул. Винниченко 12\n" +
            "квартира была в аренде два месяца, выглядит как новая!\n" +
            "ухоженный дом, высокие потолки, чистое парадное есть ЛИФТ\n" +
            "Авторский дизайн.\n" +
            "Квартира полностью укомплектована всей необходимой техникой и мебелью.",
        rating: 4.0,
        numReviews: 10,
        StockIn: false,
    }, {
        _id: "333333333333333333333333",
        name: "Оренда двохкімнатної квартири",
        category: "Квартири",
        countRooms: "2 кімнати",
        TotalArea: "30м2",
        city: "Житомир",
        street: "Героїв Небесної сотні",
        totalAction: "Довгострокова",
        numberApartmentOrHouse: "22",
        furnitureAvailability: "З меблями",
        floor: 3,
        multimedia: "Wi-Fi, телевізор і т.д",
        householdAppliances: "Стрильна мащина",
        timeCreated: "12-05-2022",
        image: "/files/apartments/images/apartment_2.jpg",
        images: [],
        price: 3000,
        Characteristics: "Сдам квартиру студию, Площадь Героев Небесной Сотни ( Бывшая Руднева ) Ремонт, мебель, техника, кондиционер. Фото соответствуют действительности. Без животных. Метро Гагарина в 10 минутах ходьбы, так же Супермаркет Класс, АТБ и другое. Оплата 6.000 свет Конт. Тел. 067-196-03-00",
        rating: 4.0,
        numReviews: 10,
        StockIn: false,
    }]
}